version: "3.8"

services:
  # Python Service
  python:
    build: "./.docker/python"
    ports:
      - 80:80
    volumes:
      - /webroot:/var/www/html/app
    networks:
        - default


networks:
  default: